blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/ageha734/mmdc/discussions
    about: Ask questions and discuss ideas
  - name: Security Vulnerabilities
    url: https://github.com/ageha734/mmdc/security/advisories/new
    about: Report critical security issues privately
